set(ARCHIVE_NAME http)
if (NOT DEFINED ARCHIVE_PATH)
    set(ARCHIVE_PATH deps/${ARCHIVE_NAME})
endif ()

include_directories(${ARCHIVE_PATH}/include/http)
file(GLOB ARCHIVE_HEADER_FILES ${ARCHIVE_PATH}/include/http/*.h)
file(GLOB ARCHIVE_SOURCE_FILES ${ARCHIVE_PATH}/src/*.c)
add_library(${ARCHIVE_NAME} ${ARCHIVE_HEADER_FILES} ${ARCHIVE_SOURCE_FILES})
target_link_libraries(${ARCHIVE_NAME} curl)
