/*
 * C Header File
 *
 * Author: Davide Di Carlo
 * Date:   February 11, 2017 
 * email:  daddinuz@gmail.com
 */

#ifndef __HTTP_METHOD_H__
#define __HTTP_METHOD_H__

#ifdef __cplusplus
extern "C" {
#endif

typedef enum http_method {
    HTTP_METHOD_DELETE,
    HTTP_METHOD_GET,
    HTTP_METHOD_HEAD,
    HTTP_METHOD_POST,
    HTTP_METHOD_PUT,
    HTTP_METHOD_CONNECT,
    HTTP_METHOD_OPTIONS,
    HTTP_METHOD_TRACE,
    HTTP_METHOD_COPY,
    HTTP_METHOD_LOCK,
    HTTP_METHOD_MKCOL,
    HTTP_METHOD_MOVE,
    HTTP_METHOD_PROPFIND,
    HTTP_METHOD_PROPPATCH,
    HTTP_METHOD_SEARCH,
    HTTP_METHOD_UNLOCK,
    HTTP_METHOD_BIND,
    HTTP_METHOD_REBIND,
    HTTP_METHOD_UNBIND,
    HTTP_METHOD_ACL,
    HTTP_METHOD_REPORT,
    HTTP_METHOD_MKACTIVITY,
    HTTP_METHOD_CHECKOUT,
    HTTP_METHOD_MERGE,
    HTTP_METHOD_MSEARCH,
    HTTP_METHOD_NOTIFY,
    HTTP_METHOD_SUBSCRIBE,
    HTTP_METHOD_UNSUBSCRIBE,
    HTTP_METHOD_PATCH,
    HTTP_METHOD_PURGE,
    HTTP_METHOD_MKCALENDAR,
    HTTP_METHOD_LINK,
    HTTP_METHOD_UNLINK
} http_method_t;

#ifdef __cplusplus
}
#endif

#endif /* __HTTP_METHOD_H__ */
